In [20]:
from transformers import AutoTokenizer

model_name = "Qwen/Qwen2.5-0.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(
    model_name
)

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

In [21]:
#AutoTokenizer : 어떤 모델을 사용할지 알려주면 그 모델에 맞는 tokenizer 종류를 알아서 찾아주는 클래스
#from_pretrained()는 객체를 만들기 전에 클래스에서 호출해서 적절한 tokenizer 객체를 만들어 반환하는 메서드

In [22]:
print(type(tokenizer ))

<class 'transformers.models.qwen2.tokenization_qwen2.Qwen2Tokenizer'>


In [23]:
text = "ERROR database timeout"

encoded = tokenizer(text)

In [24]:
model_name = "Qwen/Qwen2.5-0.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(
    model_name
)

text = """INFO server started
WARN memory usage high
ERROR database timeout"""

encoded = tokenizer(text)
print(type(tokenizer))
print(encoded["input_ids"])
print(encoded["attention_mask"])



<class 'transformers.models.qwen2.tokenization_qwen2.Qwen2Tokenizer'>
[6637, 3538, 3855, 198, 74858, 4938, 10431, 1550, 198, 3682, 4625, 9632]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [25]:
#input_ids : Tokenizer가 가지고 있는 vocabulary에서 각 token에 붙어있는 번호

In [26]:
input_ids =encoded["input_ids"]
token = tokenizer.convert_ids_to_tokens(
    input_ids
)
for token_id, token in zip(
    input_ids,
    token
):
    print(token_id, token)

6637 INFO
3538 Ġserver
3855 Ġstarted
198 Ċ
74858 WARN
4938 Ġmemory
10431 Ġusage
1550 Ġhigh
198 Ċ
3682 ERROR
4625 Ġdatabase
9632 Ġtimeout


In [27]:
ids = tokenizer.encode(text)
print(ids)
decoded_text = tokenizer.decode(ids)
print(decoded_text)

[6637, 3538, 3855, 198, 74858, 4938, 10431, 1550, 198, 3682, 4625, 9632]
INFO server started
WARN memory usage high
ERROR database timeout


In [28]:
input_Ids =tokenizer.encode(text)
print("input_ids")
print(input_ids)

tokens = tokenizer.convert_ids_to_tokens(input_ids)

print("\n tokens")
print(tokens)

decoded = tokenizer.decode(
    input_ids
)

print("\n decoded:")
print(decoded)

print("\nspecial tokens")

print("BOS token:", tokenizer.bos_token)
print("EOS token:", tokenizer.eos_token)
print("PAD token:", tokenizer.pad_token)
print("UNK token:", tokenizer.unk_token)

print("\nSpecial Token IDs")

print("BOS token id:", tokenizer.bos_token_id)
print("EOS token id:", tokenizer.eos_token_id)
print("PAD token id:", tokenizer.pad_token_id)
print("UNK token id:", tokenizer.unk_token_id)

#BOS
#→ Begin Of Sequence

#EOS
#→ End Of Sequence

#PAD
#→ Padding

#UNK
#→ Unknown

input_ids
[6637, 3538, 3855, 198, 74858, 4938, 10431, 1550, 198, 3682, 4625, 9632]

 tokens
['INFO', 'Ġserver', 'Ġstarted', 'Ċ', 'WARN', 'Ġmemory', 'Ġusage', 'Ġhigh', 'Ċ', 'ERROR', 'Ġdatabase', 'Ġtimeout']

 decoded:
INFO server started
WARN memory usage high
ERROR database timeout

special tokens
BOS token: None
EOS token: <|im_end|>
PAD token: <|endoftext|>
UNK token: None

Special Token IDs
BOS token id: None
EOS token id: 151645
PAD token id: 151643
UNK token id: None


In [29]:
text = "ERROR database timeout"
encoded_true = tokenizer(
    text,
    add_special_tokens = True
)
encoded_false = tokenizer(
    text,
    add_special_tokens = False
)

print(encoded_true["input_ids"])
print(encoded_false["input_ids"])
print(tokenizer.special_tokens_map)

[3682, 4625, 9632]
[3682, 4625, 9632]
{'eos_token': '<|im_end|>', 'pad_token': '<|endoftext|>'}


In [30]:
#Padding 쉽게 말하면 데이터의 길이·크기를 맞추기 위해 의미 없는 값을 채워 넣는 것
texts = [
    "ERROR timeout",
    "INFO server successfully started"
]
token = tokenizer(
    texts,
    padding = True
)
print(encoded["input_ids"])
print(encoded["attention_mask"])

[6637, 3538, 3855, 198, 74858, 4938, 10431, 1550, 198, 3682, 4625, 9632]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [31]:
texts = [
    "ERROR timeout",
    "INFO server successfully started",
    "WARN database connection failed because server response timeout"
]
encoded = tokenizer(
    texts,
    truncation = True,
    padding="max_length",
    max_length = 6
) # max_length 는 토큰 개수

print(encoded["input_ids"])
print(encoded["attention_mask"])


[[3682, 9632, 151643, 151643, 151643, 151643], [6637, 3538, 7790, 3855, 151643, 151643], [74858, 4625, 3633, 4641, 1576, 3538]]
[[1, 1, 0, 0, 0, 0], [1, 1, 1, 1, 0, 0], [1, 1, 1, 1, 1, 1]]


In [32]:
text = """INFO server started
WARN memory usage high
ERROR database timeout"""

encoded = tokenizer(
    text,
    return_offsets_mapping = True,
    add_special_tokens = False
)
input_ids = encoded["input_ids"]
offsets = encoded["offset_mapping"]

tokens = tokenizer.convert_ids_to_tokens(input_ids)
for token_id,token ,(start,end) in zip( input_ids,
    tokens,
    offsets):
  original_text = text[start:end]
  print(token_id,start,end,token,
  repr(original_text)
    )

6637 0 4 INFO 'INFO'
3538 4 11 Ġserver ' server'
3855 11 19 Ġstarted ' started'
198 19 20 Ċ '\n'
74858 20 24 WARN 'WARN'
4938 24 31 Ġmemory ' memory'
10431 31 37 Ġusage ' usage'
1550 37 42 Ġhigh ' high'
198 42 43 Ċ '\n'
3682 43 48 ERROR 'ERROR'
4625 48 57 Ġdatabase ' database'
9632 57 65 Ġtimeout ' timeout'


In [33]:

current_pos = 0
texts = """INFO server started
WARN memory usage high
ERROR database timeout"""
for line_idx,line in enumerate(texts.splitlines()):
   line_start = current_pos
   line_end = line_start+len(line)

   print(line_idx, line_start, line_end, line)

   current_pos = line_end + 1


0 0 19 INFO server started
1 20 42 WARN memory usage high
2 43 65 ERROR database timeout


In [34]:
encoded = tokenizer(
    texts,
    return_tensors="pt"
)
print(encoded["input_ids"])
print(type(encoded["input_ids"]))
print(encoded["input_ids"].shape)
print(encoded["attention_mask"].shape)

tensor([[ 6637,  3538,  3855,   198, 74858,  4938, 10431,  1550,   198,  3682,
          4625,  9632]])
<class 'torch.Tensor'>
torch.Size([1, 12])
torch.Size([1, 12])


In [35]:
import torch

keys = torch.rand(2,8,20,64)

print(keys)
print(keys.shape)

B, H, T, Dh = keys.shape

print(B)
print(H)
print(T)
print(Dh)

tensor([[[[0.6464, 0.3950, 0.3100,  ..., 0.3741, 0.2350, 0.7714],
          [0.0880, 0.5663, 0.7632,  ..., 0.1141, 0.8357, 0.8714],
          [0.9213, 0.1001, 0.6144,  ..., 0.7302, 0.7592, 0.4322],
          ...,
          [0.1483, 0.9838, 0.9931,  ..., 0.7938, 0.0859, 0.1238],
          [0.5754, 0.5377, 0.2980,  ..., 0.9911, 0.3896, 0.4893],
          [0.6217, 0.5427, 0.9284,  ..., 0.3256, 0.9293, 0.3002]],

         [[0.3456, 0.2885, 0.8621,  ..., 0.2316, 0.6948, 0.5566],
          [0.6040, 0.2149, 0.9471,  ..., 0.9294, 0.5062, 0.3611],
          [0.0454, 0.6312, 0.5336,  ..., 0.9292, 0.2397, 0.6542],
          ...,
          [0.7246, 0.0899, 0.6603,  ..., 0.4139, 0.7711, 0.2603],
          [0.7091, 0.6403, 0.6767,  ..., 0.7538, 0.8141, 0.7092],
          [0.2909, 0.9530, 0.7415,  ..., 0.8270, 0.8578, 0.4990]],

         [[0.6189, 0.3608, 0.2268,  ..., 0.1804, 0.7453, 0.3254],
          [0.3051, 0.3556, 0.0016,  ..., 0.7017, 0.1111, 0.9959],
          [0.3924, 0.3208, 0.5880,  ..., 0

In [36]:
import torch

keys = torch.randn(3,4,10,32)

print("전체 shape:" , keys.shape)

B,H,T,Dh = keys.shape

print("B :",B)
print("H :",H)
print("T :",T)
print("Dh :",Dh)

전체 shape: torch.Size([3, 4, 10, 32])
B : 3
H : 4
T : 10
Dh : 32


In [37]:
import torch

x = torch.tensor([
    [10, 20, 30, 40],
    [50, 60, 70, 80]
])
print(x)
print(x.shape)

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])
torch.Size([2, 4])


In [38]:
import torch

keys = torch.randn(2, 8, 20, 64)
recent_keys =keys[:,:,-6:,:]
print(keys.shape)
print(recent_keys.shape)

torch.Size([2, 8, 20, 64])
torch.Size([2, 8, 6, 64])


In [39]:
#reshape()
#→ shape 변경
#→ 필요하면 내부적으로 copy 가능
#→ 좀 더 편하게 사용 가능

#view()
#→ shape 변경
#→ 메모리 구조 조건이 더 까다로움
#→ underlying data를 공유하는 view
x = torch.randn(2, 12, 256)
B,T,D =x.shape
H=8
Dh=D//H
x = x.reshape(B,T,H,Dh)

print(x.shape)

torch.Size([2, 12, 8, 32])


In [40]:
#transpose 는 두차원만 바꿈

x.transpose(1,2)

#permute()는 전체 축 순서를 직접 지정
x.permute(0,2,1,3)

x= torch.randn(2,10,4,64)
y = x.transpose(1,2)
z = x .permute(2,0,1 ,3)
print(y.shape)
print(z.shape)

torch.Size([2, 4, 10, 64])
torch.Size([4, 2, 10, 64])


In [41]:
x = torch.tensor([10, 20, 30])
print(x.shape)
y = x.unsqueeze(0)

print(y)
print(y.shape)

x = torch.tensor([
    [10, 20, 30]
])

print(x.shape)

y = x.squeeze(0) # 크기가 1차원만 제거

print(y.shape)

torch.Size([3])
tensor([[10, 20, 30]])
torch.Size([1, 3])
torch.Size([1, 3])
torch.Size([3])


In [42]:
x= torch.randn(2,10)
print(x.shape)
y=x.unsqueeze(1)
y=y.unsqueeze(2)
print(y.shape)

y=y.squeeze()
print(y.shape)

torch.Size([2, 10])
torch.Size([2, 1, 1, 10])
torch.Size([2, 10])


In [43]:

a = torch.tensor([
    [1, 2],
    [3, 4]
])

b = torch.tensor([
    [5, 6],
    [7, 8]
])

In [44]:
old_keys = torch.randn(2, 4, 10, 32)
new_keys = torch.randn(2, 4, 3, 32)
keys = torch.cat([old_keys,new_keys],dim=2)
print(old_keys.shape)
print(new_keys.shape)
print(keys.shape)

torch.Size([2, 4, 10, 32])
torch.Size([2, 4, 3, 32])
torch.Size([2, 4, 13, 32])


In [45]:
a = torch.tensor([
    [1, 2],
    [3, 4]
])

b = torch.tensor([
    [5, 6],
    [7, 8]
])

c1= torch.matmul(a,b)
c2 = a@b

print(c1)
print(c2)

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [46]:
Q = torch.randn(2, 8, 20, 32)
K = torch.randn(2, 8, 20, 32)

K_T = K.transpose(-2,-1)
scores = Q @ K_T
print(K_T.shape)
print(scores.shape)

torch.Size([2, 8, 32, 20])
torch.Size([2, 8, 20, 20])


In [47]:
#softmax : score값을 비율로 변환

Q = torch.randn(2,4,10,64)
K = torch.randn(2,4,10,64)

scores = Q @ K.transpose(-2,-1)

weights = torch.softmax(
    scores,
    dim= -1
)

print(scores.shape)
print(weights.shape)

print(weights.sum(dim=-1))

torch.Size([2, 4, 10, 10])
torch.Size([2, 4, 10, 10])
tensor([[[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
          1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
          1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
          1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
          1.0000, 1.0000]],

        [[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
          1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
          1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
          1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
          1.0000, 1.0000]]])


In [48]:
scores = torch.tensor([
    0.1,
    0.8,
    0.3,
    0.9,
    0.2
])

values ,indices = torch.topk(scores, k = 3 )

print(values)
print(indices)

tensor([0.9000, 0.8000, 0.3000])
tensor([3, 1, 2])


In [49]:
keys = torch.randn(2, 8, 10, 64)

scores = torch.tensor([
    0.1,
    0.7,
    0.2,
    0.9,
    0.3,
    0.8,
    0.4,
    0.6,
    0.5,
    0.05
])
values,indices = torch.topk(
    scores, k =4
)

print("values :", values)
print("indices:", indices)

selected_keys= torch.index_select(
    keys,
    dim = 2,
    index = indices
)
print("원래 keys:", keys.shape)
print("선택 keys:", selected_keys.shape)


values : tensor([0.9000, 0.8000, 0.7000, 0.6000])
indices: tensor([3, 5, 1, 7])
원래 keys: torch.Size([2, 8, 10, 64])
선택 keys: torch.Size([2, 8, 4, 64])


In [50]:
#gather : 각 행마다 서로 다른 index를 줄 수있음
scores = torch.tensor([
    [
        [0.1, 0.7, 0.2, 0.9, 0.3],
        [0.8, 0.2, 0.6, 0.1, 0.5]
    ]
])

values, indices = torch.topk(
    scores,
    k=2,
    dim = -1
)
print(values)
print(indices)
print(indices.shape)

tensor([[[0.9000, 0.7000],
         [0.8000, 0.6000]]])
tensor([[[3, 1],
         [0, 2]]])
torch.Size([1, 2, 2])


In [51]:
x = torch.randn(3,4)
A = x.unsqueeze(0)
B = x.unsqueeze(1)
C = x.unsqueeze(2)

print(A.shape)
print(B.shape)
print(C.shape)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [54]:
x = torch.randn(1,3,1,5)
A = x.squeeze()
B = x.squeeze(2)

print(A.shape)
print(B.shape)

torch.Size([3, 5])
torch.Size([1, 3, 5])


In [55]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
A = torch.stack([a,b],dim = 1)
B = torch.stack([a,b],dim = 0)
print(A.shape)
print(A)
print(B)
print(B.shape)

torch.Size([3, 2])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [ ]:
a = torch.randn(2, 3)
b = torch.randn(2, 3)
c = torch.randn(2, 3)